### ISSUE TITLE
first bug report

### ISSUE THREAD

**Issue by SeanFlattery-PFG** [b-diggity/gitgit#18]
README file should change
if [ ! -f ~/.ssh/id_rsa ]; then ssh-keygen -t rsa -q -N '' -f ~/.ssh/id_rsa; fi; cat ~/.ssh/id_rsa
to
if [ ! -f ~/.ssh/id_rsa ]; then ssh-keygen -t rsa -q -N '' -f ~/.ssh/id_rsa; fi; cat ~/.ssh/id_rsa.pub

**Comment by rssnyder** [comment]
this is URGENT we are stuck, SEV 2 issued.

**Comment by b-diggity** [comment]
> this is URGENT we are stuck, SEV 2 issued.

Crisis adverted!
